# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bePOSChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'RxAlamofire'
    pod 'Alamofire'
    pod 'RealmSwift'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'SDWebImage', '~> 5.0'
    pod 'Charts'
    pod 'JGProgressHUD'
  target 'bePOSChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bePOSChallengeUITests' do
    # Pods for testing
  end

end
